-- =====================================================================
-- REMOTE BASELINE — 제주 새활용 도감 (public schema)
-- =====================================================================
-- 이 파일은 2026-06-29 시점의 원격 Supabase(public 스키마) 전체 상태를
-- 코드로 떠둔 baseline 마이그레이션입니다. 그동안 대시보드에서 직접 만든
-- 스키마(테이블·제약·RLS·함수·트리거·스토리지)를 SQL로 일괄 재현합니다.
--
-- 모든 구문은 멱등(idempotent)하게 작성되어 있어 여러 번 적용해도 안전합니다.
-- 앞으로 스키마 변경은 대시보드가 아니라 supabase/migrations/ 에 새 .sql 파일을
-- 추가하고 `node supabase/scripts/run-sql.mjs <file>` 으로 적용하세요.
-- (자세한 워크플로는 supabase/README.md 참고)
--
-- project_ref: qotyklxakmqfehgvsouq
-- =====================================================================

-- ===== 1. ENUM 타입 =====
do $$ begin
  if not exists (select 1 from pg_type where typname = 'match_status') then
    create type public.match_status as enum ('interested','accepted','declined','completed','failed');
  end if;
  if not exists (select 1 from pg_type where typname = 'post_status') then
    create type public.post_status as enum ('active','closed');
  end if;
  if not exists (select 1 from pg_type where typname = 'post_type') then
    create type public.post_type as enum ('offer','request');
  end if;
end $$;

-- ===== 2. 테이블 =====
-- 사용자 (auth.users 와 1:1, id 동일). "user" 는 예약어라 항상 따옴표 필요.
create table if not exists public."user" (
  id              uuid primary key default gen_random_uuid(),
  created_at      timestamptz not null default now(),
  email           text,
  nickname        text,
  phone           text,
  terms_agreed_at timestamptz,
  bio             text
);

-- 게시글 (있어요 / 구해요)
create table if not exists public.posts (
  id            bigint generated by default as identity primary key,
  author_id     uuid not null references public."user"(id) on delete cascade,
  post_type     public.post_type not null,
  title         text not null,
  body          text not null,
  region        text not null,
  image_url     text,
  status        public.post_status not null default 'active',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  contact_email text,
  amount        text,
  timing        text
);

-- 매칭
create table if not exists public.matches (
  id                  bigint generated by default as identity primary key,
  initiator_id        uuid not null references public."user"(id) on delete cascade,
  post_id             bigint not null references public.posts(id) on delete cascade,
  post_author_id      uuid not null references public."user"(id) on delete cascade,
  message             text not null,
  status              public.match_status not null default 'interested',
  contact_revealed_at timestamptz,
  status_history      jsonb not null default '[]'::jsonb,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  constraint unique_match unique (initiator_id, post_id),
  constraint no_self_match check (initiator_id <> post_author_id)
);

-- 좋아요
create table if not exists public.likes (
  id         bigint generated always as identity primary key,
  user_id    uuid not null references public."user"(id) on delete cascade,
  post_id    bigint not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint likes_user_id_post_id_key unique (user_id, post_id)
);

-- 이메일 연락 이력
create table if not exists public.email_contacts (
  id        bigint generated always as identity primary key,
  sender_id uuid not null references public."user"(id) on delete cascade,
  post_id   bigint not null references public.posts(id) on delete cascade,
  sent_at   timestamptz not null default now(),
  constraint email_contacts_sender_id_post_id_key unique (sender_id, post_id)
);

-- 차단
create table if not exists public.blocks (
  id         bigint generated by default as identity primary key,
  blocker_id uuid not null references public."user"(id) on delete cascade,
  blocked_id uuid not null references public."user"(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint unique_block unique (blocker_id, blocked_id),
  constraint no_self_block check (blocker_id <> blocked_id)
);

-- 신고
create table if not exists public.reports (
  id             bigint generated by default as identity primary key,
  reporter_id    uuid not null references public."user"(id) on delete cascade,
  target_user_id uuid not null references public."user"(id) on delete cascade,
  match_id       bigint references public.matches(id) on delete set null,
  reason         text not null,
  status         text not null default 'pending',
  created_at     timestamptz not null default now(),
  constraint reports_status_check check (status = any (array['pending','reviewed','resolved']))
);

-- ===== 3. 함수 =====
-- 신규 auth 사용자 → public."user" 자동 생성
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public."user" (id, email)
  values (new.id, new.email);
  return new;
end;
$$;

-- updated_at 자동 갱신
create or replace function public.update_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ===== 4. 트리거 =====
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

drop trigger if exists posts_updated_at on public.posts;
create trigger posts_updated_at
  before update on public.posts
  for each row execute function public.update_updated_at();

drop trigger if exists matches_updated_at on public.matches;
create trigger matches_updated_at
  before update on public.matches
  for each row execute function public.update_updated_at();

-- ===== 5. 권한 (Supabase 기본 grant) =====
grant all on table public."user"           to anon, authenticated, service_role;
grant all on table public.posts            to anon, authenticated, service_role;
grant all on table public.matches          to anon, authenticated, service_role;
grant all on table public.likes            to anon, authenticated, service_role;
grant all on table public.email_contacts   to anon, authenticated, service_role;
grant all on table public.blocks           to anon, authenticated, service_role;
grant all on table public.reports          to anon, authenticated, service_role;

-- ===== 6. RLS 활성화 =====
alter table public."user"         enable row level security;
alter table public.posts          enable row level security;
alter table public.matches        enable row level security;
alter table public.likes          enable row level security;
alter table public.email_contacts enable row level security;
alter table public.blocks         enable row level security;
alter table public.reports        enable row level security;

-- ===== 7. RLS 정책 =====
-- user: 연락처(phone/email)는 행 단위로 보호. 현재 정책은 전체 컬럼 SELECT 를
--       본인/공개로 나눠 두 정책으로 운영. (공개 프로필 조회는 닉네임·bio 노출 목적)
drop policy if exists "user: 공개 프로필 조회" on public."user";
create policy "user: 공개 프로필 조회" on public."user"
  for select using (true);

drop policy if exists "user: 본인 조회" on public."user";
create policy "user: 본인 조회" on public."user"
  for select using (auth.uid() = id);

drop policy if exists "user: 본인 수정" on public."user";
create policy "user: 본인 수정" on public."user"
  for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "user: 트리거 insert 허용" on public."user";
create policy "user: 트리거 insert 허용" on public."user"
  for insert with check (true);

-- posts
drop policy if exists "posts: 활성 게시글 공개 조회" on public.posts;
create policy "posts: 활성 게시글 공개 조회" on public.posts
  for select using (status = 'active'::post_status);

drop policy if exists "posts: 본인 게시글 전체 조회" on public.posts;
create policy "posts: 본인 게시글 전체 조회" on public.posts
  for select using (auth.uid() = author_id);

drop policy if exists "posts: 작성" on public.posts;
create policy "posts: 작성" on public.posts
  for insert with check (auth.uid() = author_id);

drop policy if exists "posts: 본인 수정" on public.posts;
create policy "posts: 본인 수정" on public.posts
  for update using (auth.uid() = author_id) with check (auth.uid() = author_id);

drop policy if exists "posts: 본인 삭제" on public.posts;
create policy "posts: 본인 삭제" on public.posts
  for delete using (auth.uid() = author_id);

-- matches: 당사자(신청자/게시글 작성자)만 접근
drop policy if exists "matches: 당사자만 조회" on public.matches;
create policy "matches: 당사자만 조회" on public.matches
  for select using ((auth.uid() = initiator_id) or (auth.uid() = post_author_id));

drop policy if exists "matches: 신청 작성" on public.matches;
create policy "matches: 신청 작성" on public.matches
  for insert with check ((auth.uid() = initiator_id) and (auth.uid() <> post_author_id));

drop policy if exists "matches: 당사자 상태 변경" on public.matches;
create policy "matches: 당사자 상태 변경" on public.matches
  for update using ((auth.uid() = initiator_id) or (auth.uid() = post_author_id));

-- likes
drop policy if exists "likes: 집계 공개 조회" on public.likes;
create policy "likes: 집계 공개 조회" on public.likes
  for select using (true);

drop policy if exists "likes: 본인 좋아요 조회" on public.likes;
create policy "likes: 본인 좋아요 조회" on public.likes
  for select using (auth.uid() = user_id);

drop policy if exists "likes: 좋아요 추가" on public.likes;
create policy "likes: 좋아요 추가" on public.likes
  for insert with check (auth.uid() = user_id);

drop policy if exists "likes: 좋아요 취소" on public.likes;
create policy "likes: 좋아요 취소" on public.likes
  for delete using (auth.uid() = user_id);

-- email_contacts
drop policy if exists "email_contacts: 본인 이력 조회" on public.email_contacts;
create policy "email_contacts: 본인 이력 조회" on public.email_contacts
  for select using (auth.uid() = sender_id);

drop policy if exists "email_contacts: 이력 추가" on public.email_contacts;
create policy "email_contacts: 이력 추가" on public.email_contacts
  for insert with check (auth.uid() = sender_id);

-- blocks
drop policy if exists "blocks: 본인 차단 목록 조회" on public.blocks;
create policy "blocks: 본인 차단 목록 조회" on public.blocks
  for select using (auth.uid() = blocker_id);

drop policy if exists "blocks: 차단 작성" on public.blocks;
create policy "blocks: 차단 작성" on public.blocks
  for insert with check (auth.uid() = blocker_id);

drop policy if exists "blocks: 차단 해제" on public.blocks;
create policy "blocks: 차단 해제" on public.blocks
  for delete using (auth.uid() = blocker_id);

-- reports
drop policy if exists "reports: 본인 신고 조회" on public.reports;
create policy "reports: 본인 신고 조회" on public.reports
  for select using (auth.uid() = reporter_id);

drop policy if exists "reports: 신고 작성" on public.reports;
create policy "reports: 신고 작성" on public.reports
  for insert with check (auth.uid() = reporter_id);

-- ===== 8. 스토리지 (post-images 버킷, 공개) =====
insert into storage.buckets (id, name, public)
values ('post-images', 'post-images', true)
on conflict (id) do nothing;

drop policy if exists "post-images: public read" on storage.objects;
create policy "post-images: public read" on storage.objects
  for select using (bucket_id = 'post-images');

drop policy if exists "post-images: authenticated upload" on storage.objects;
create policy "post-images: authenticated upload" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'post-images' and (storage.foldername(name))[1] = (auth.uid())::text);

drop policy if exists "post-images: owner delete" on storage.objects;
create policy "post-images: owner delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'post-images' and (storage.foldername(name))[1] = (auth.uid())::text);
